return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "cmake",
      "csv",
      "dockerfile",
      "git_config",
      "gitcommit",
      "gitignore",
      "gomod",
      "gosum",
      "go",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "sql",
      "regex",
      "terraform",
      "vim",
      "yaml",
    },
  },
}
